sudo: false
language: rust
os:
  - osx
matrix:
  # Early fail/finish build if jobs fail
  fast_finish: true
  include:
    - rust: stable # to stay up to date
    - rust: beta # because the Rust team appreciates it
    - rust: nightly
before_install:
  # Add Rust binaries to path
  - export PATH="$HOME/.cargo/bin:$PATH"
script:
  - cargo build --verbose
  - cargo test --verbose
cache: cargo